- src/org/jitsi/impl/neomedia/codec/video/vp8/VPXDecoder.java
> Input buffer timestamp used instead of setting as unknown

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/RawPacket.java
- src/org/jitsi/impl/neomedia/codec/video/vp8/DePacketizer.java
- src/org/jitsi/impl/neomedia/rtcp/termination/strategies/BasicRTCPTerminationStrategy.java
- src/org/jitsi/impl/neomedia/rtcp/termination/strategies/MinThroughputRTCPTerminationStrategy.java
- src/org/jitsi/impl/neomedia/transform/SsrcRewritingEngine.java
- src/org/jitsi/service/neomedia/MediaStream.java
- src/org/jitsi/util/function/RTCPGenerator.java
Nobody's using SSRC rewriting currently. The simulcast functionality will be using it and it's coming by the end of this week, hopefully.
> Implements SSRC rewriting (experimental).

- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RecurringProcessible.java
- src/org/jitsi/impl/neomedia/rtp/sendsidebandwidthestimation/BandwidthEstimatorImpl.java
- src/org/jitsi/impl/neomedia/rtp/sendsidebandwidthestimation/SendSideBandwidthEstimation.java
These are the results of routine background maintenance performed by me while looking at source code for the purposes of other issues.
> Removes unnecessary source code, adds javadocs

- src/org/jitsi/impl/configuration/ConfigurationServiceImpl.java
- src/org/jitsi/service/configuration/ConfigurationService.java
> Adds getDouble() to ConfigurationService

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/RawPacket.java
- src/org/jitsi/impl/neomedia/VideoMediaStreamImpl.java
- src/org/jitsi/impl/neomedia/transform/AbsSendTimeEngine.java
- src/org/jitsi/impl/neomedia/transform/csrc/CsrcTransformEngine.java
to packets which don't have one.
> Add an abs-send-time RTP header extension

- src/org/jitsi/util/concurrent/MonotonicAtomicLong.java
To be used in jitsi-videobridge.
> Adds the MonotonicAtomicLong utility class.

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
Allows MediaStream#setTarget() to be called before #setConnector(). This is part of a fix for a problem with jitsi-videobridge, where we want to ensure we have a target before we set a connector, because the latter starts DTLS and it may try to send packets. See a discussion here: http://lists.jitsi.org/pipermail/dev/2016-March/027119.html
>  Allows MediaStream#setTarget() to be called before #setConnector().

- src/org/jitsi/impl/neomedia/transform/srtp/SRTCPCryptoContext.java
- src/org/jitsi/impl/neomedia/transform/srtp/SRTPCryptoContext.java
> Use constant time comparison to check authentication tag

- src/org/jitsi/impl/neomedia/RawPacket.java
> RawPacket: only grow internal buffer when really needed

- pom.xml
- src/org/jitsi/impl/neomedia/transform/dtls/DtlsPacketTransformer.java
- src/org/jitsi/impl/neomedia/transform/dtls/TlsClientImpl.java
- src/org/jitsi/impl/neomedia/transform/dtls/TlsServerImpl.java
Pulls https://github.com/jitsi/libjitsi/pull/72 from champtar's fork into jitsi/libjitsi's branch to enable further automatic testing.
> Update boncycastle from 1.51 to 1.54

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/RawPacket.java
- src/org/jitsi/impl/neomedia/VideoMediaStreamImpl.java
- src/org/jitsi/impl/neomedia/transform/RetransmissionRequesterImpl.java
- src/org/jitsi/impl/neomedia/transform/rewriting/ExtendedSequenceNumberInterval.java
- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcGroupRewriter.java
- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcRewriter.java
- src/org/jitsi/service/neomedia/MediaStream.java
- src/org/jitsi/service/neomedia/RetransmissionRequester.java
Recognizes packets retransmitted with RTX and doesn't request them again.
> Fixes and improvements for RTX.

- src/org/jitsi/impl/neomedia/device/AudioMediaDeviceSession.java
- src/org/jitsi/impl/neomedia/device/AudioSilenceCaptureDevice.java
- src/org/jitsi/impl/neomedia/device/AudioSilenceMediaDevice.java
Moves the "audio silence" devices from jitsi-videobridge to libjitsi,
because they are also used in jitsi-hammer.
> Moves AudioSilence{Media,Capture}Device to libjitsi.

- src/org/jitsi/impl/neomedia/rtp/translator/RTCPFeedbackMessageSender.java
In response to @gpolitis and conversation [here](https://github.com/jitsi/libjitsi/pull/145/files/7cdebacba6539fab0a9ae8a2f715889223009ce9#r60075218)
I didn't see a quick and easy way to test this, but basic sanity checks seem to pass (e.g. the videobridge runs and serves video).
> Less locking but also less unnecessary new objects.

- src/org/jitsi/examples/AVReceive2.java
- src/org/jitsi/examples/AVTransmit2.java
- src/org/jitsi/impl/configuration/ConfigurationServiceImpl.java
- src/org/jitsi/impl/neomedia/codec/audio/ilbc/JavaDecoder.java
- src/org/jitsi/impl/neomedia/codec/audio/ilbc/JavaEncoder.java
- src/org/jitsi/impl/neomedia/codec/audio/silk/SigProcFIX.java
- src/org/jitsi/impl/neomedia/notify/AudioNotifierServiceImpl.java
- src/org/jitsi/impl/neomedia/recording/RecorderEventHandlerJSONImpl.java
- src/org/jitsi/impl/neomedia/rtcp/termination/strategies/FeedbackCacheProcessor.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/InterArrival.java
- src/org/jitsi/impl/neomedia/transform/zrtp/ZRTPTransformEngine.java
- src/org/jitsi/service/version/util/AbstractVersion.java
This is a collections of really simple fixes, that's why i'm not opening a PR for each
> Fixes for simple bugs found with FindBugs

- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/OveruseEstimator.java
this avoid a lot of autoboxing, and is more efficient
> OveruseEstimator replace LinkedList<Double> with double[]

- src/org/jitsi/service/neomedia/MediaType.java
A trivial change to also support a "message" media description.
> Support "message" media type.

- pom.xml
- src/org/jitsi/impl/neomedia/device/DeviceConfiguration.java
- src/org/jitsi/impl/neomedia/transform/srtp/AES.java
- Maven dependency error
- Reference to a disabled component
- Duplicate initialization
> Three little fixes

- src/org/jitsi/impl/neomedia/RawPacket.java
- src/org/jitsi/impl/neomedia/rtp/translator/OutputDataStreamImpl.java
- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcGroupRewriter.java
- src/org/jitsi/util/RTPUtils.java
This is PR includes the libjitsi changes required for sequence number rewriting. In addition to some helper functions, we a seq number reset logic is added to make sure the rewriting works fine.
> libjitsi changes for sequence number rewriting for video packets.

- pom.xml
- src/org/jitsi/impl/neomedia/RTPConnectorOutputStream.java
- src/org/jitsi/impl/neomedia/rtp/translator/OutputDataStreamImpl.java
- src/org/jitsi/impl/neomedia/rtp/translator/PushSourceStreamImpl.java
- src/org/jitsi/impl/neomedia/transform/CachingTransformer.java
- src/org/jitsi/util/InstanceLogger.java
- src/org/jitsi/util/Logger.java
- src/org/jitsi/util/LoggerImpl.java
> Refactors Logger. Adds a second Logger implementation with more flexible

- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/InterArrival.java
https://github.com/jitsi/libjitsi/issues/212
> Fix a reference assignment of prevTimestampGroup to correctly be a copy

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
> Fix MediaStreamStats access prior to initialization

- src/org/jitsi/util/JNIUtils.java
A native library is normally loaded and bound to the ClassLoader of
the class calling System.loadLibray. If this task is delegated to a
utility method like in JNIUtils, and JNIUtils itself is in a different
ClassLoader than the caller, the native library won't be available to
the caller.
Add a method that passes the calling class and call the Runtime via
reflection with this passed class so that the native library ends up
in the ClassLoader of the class that calls JNIUtils.
> Add support for real OSGi in JNIUtils

- src/native/sctp/README.md
this is what i think i've distilled my workflow down to, which uses the new method (not the old shared lib thing).  if this looks good then i think we should also probably clean up some of the other files.
> new README.md file for building the usrsctp lib.

- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackReceiver.java
Thanks to @JVBK for the notice.
> fix: Fixes an incorrect for loop condition.

- src/org/jitsi/impl/neomedia/transform/RtxTransformer.java
This reverts commit 355069199c665eecbdba24b91d66d3b6659ba84a.
> Revert "fix: Don't count packets which failed to retransmit."

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/MediaUtils.java
- src/org/jitsi/impl/neomedia/codec/video/vp8/DePacketizer.java
- src/org/jitsi/impl/neomedia/codec/video/vp9/DePacketizer.java
- src/org/jitsi/impl/neomedia/transform/RtxTransformer.java
- src/org/jitsi/service/neomedia/codec/Constants.java
This PR is not about VP9 SVC filtering & rewriting, it's about correctly handling VP9 and also some modifications to the RtxTransformer so that it correctly handles RTX from multiple codecs.
> Adds VP9 support.

- doc/parameters.md
Corrected the explanation of the boolean fields; net.java.sip.communicator.service.media.DISABLE\_AUDIO\_SUPPORT  and net.java.sip.communicator.service.media.DISABLE\_VIDEO\_SUPPORT
> Corrected documentation on MediaServiceImpl

- src/org/jitsi/impl/neomedia/rtp/RawPacketCache.java
> fix: Fixes a bug which brakes retransmissions (introduced with

- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackDesc.java
- src/org/jitsi/impl/neomedia/rtp/RTPEncodingDesc.java
- src/org/jitsi/impl/neomedia/rtp/sendsidebandwidthestimation/SendSideBandwidthEstimation.java
This PR is required for https://github.com/jitsi/jitsi-videobridge/pull/446. For context on why this PR is necessary and what this PR tries to achieve, have a look at the JVB PR description.
> Bandwidth estimation and probing for bandwidth fixes

- src/org/jitsi/impl/neomedia/transform/AbsSendTimeEngine.java
added to packets which don't already have an extension.
> fix: Fixes the length of the abs-send-time extension

- src/org/jitsi/impl/neomedia/device/AudioSilenceSystem.java
- src/org/jitsi/impl/neomedia/jmfext/media/protocol/audiosilence/DataSource.java
That thread is not needed in translator mode.
> Adds an option to AudioSilenceStream to disable transfer.

- src/org/jitsi/impl/neomedia/rtp/FrameMarkingHeaderExtension.java
Bit operation was wrong, all frames were marked as I frames (S bit set) 
cc/ @bgrozev
> Fix FrameMarking isKeyframe

- pom.xml
- src/org/jitsi/impl/neomedia/device/AudioMixerMediaDevice.java
- src/org/jitsi/impl/neomedia/device/ReceiveStreamBufferListener.java
Add a ReceiveStreamBufferListener to AudioMixerMediaDevice such that audio can be acceded before it's mixed
> ReceiveSreamBufferListener

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/MediaUtils.java
- src/org/jitsi/impl/neomedia/codec/video/h264/DePacketizer.java
- src/org/jitsi/impl/neomedia/codec/video/vp8/DePacketizer.java
- src/org/jitsi/impl/neomedia/rtp/FrameDesc.java
- src/org/jitsi/impl/neomedia/rtp/RTPEncodingDesc.java
- src/org/jitsi/impl/neomedia/transform/RtxTransformer.java
- src/org/jitsi/service/neomedia/AbstractMediaStream.java
- src/org/jitsi/service/neomedia/MediaStream.java
- src/org/jitsi/service/neomedia/RawPacket.java
This is providing https://github.com/jitsi/jitsi-videobridge/pull/504
> Unbreaks H264 support in the bridge.

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/MediaStreamStatsImpl.java
- src/org/jitsi/impl/neomedia/VideoMediaStreamImpl.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPFBPacket.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPReceiverFeedbackTermination.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPTCCPacket.java
- src/org/jitsi/impl/neomedia/rtp/TransportCCEngine.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/AimdRateControl.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/InterArrival.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/OveruseEstimator.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorAbsSendTime.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorSingleStream.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorWrapper.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateObserver.java
- src/org/jitsi/impl/neomedia/rtp/sendsidebandwidthestimation/BandwidthEstimatorImpl.java
- src/org/jitsi/impl/neomedia/rtp/sendsidebandwidthestimation/SendSideBandwidthEstimation.java
- src/org/jitsi/impl/neomedia/transform/AbsSendTimeEngine.java
- src/org/jitsi/impl/neomedia/transform/OriginalHeaderBlockTransformEngine.java
- src/org/jitsi/service/neomedia/MediaStream.java
- src/org/jitsi/service/neomedia/RTPExtension.java
- src/org/jitsi/service/neomedia/VideoMediaStream.java
- src/org/jitsi/service/neomedia/rtp/BandwidthEstimator.java
- src/org/jitsi/service/neomedia/rtp/CallStatsObserver.java
- src/org/jitsi/service/neomedia/rtp/RemoteBitrateEstimator.java
- src/org/jitsi/util/RTPUtils.java
- test/org/jitsi/impl/neomedia/rtcp/RTCPTCCPacketTest.java
Depends on https://github.com/jitsi/jicofo/pull/216
Provides https://github.com/jitsi/jitsi-videobridge/pull/529
> feat: Implements send-side bandwidth estimations.

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPReceiverFeedbackTermination.java
- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackDesc.java
- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackReceiver.java
- src/org/jitsi/impl/neomedia/rtp/RTPEncodingDesc.java
- src/org/jitsi/impl/neomedia/rtp/TransportCCEngine.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorWrapper.java
- src/org/jitsi/impl/neomedia/transform/RtxTransformer.java
Removes some deprecated methods from MediaStreamImpl (just the Impl)
> Minor cleanup and refactoring

- src/org/jitsi/impl/neomedia/transform/rtcp/StatisticsEngine.java
- src/org/jitsi/util/ByteBufferOutputStream.java
this is part of the effort to remove the fmj dependency
> bring ByteBufferOutputStream from fmj

- src/org/jitsi/util/ByteBufferOutputStream.java
> fix incorrect class package path after moving from fmj

- src/org/jitsi/service/neomedia/rtp/RTCPExtendedReport.java
> fix: Fixes parsing of RTCP XR VoIP metrics blocks.

- doc/parameters.md
- src/org/jitsi/impl/neomedia/transform/fec/AbstractFECReceiver.java
- src/org/jitsi/impl/neomedia/transform/fec/FECTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/fec/ULPFECReceiver.java
- src/org/jitsi/util/RTPUtils.java
Add an AbstractFECReceiver layer so that we can have both ulpfec and
flexfec implementations.
> Add a layer of abstraction to support multiple fec types

- src/org/jitsi/impl/configuration/ConfigurationServiceImpl.java
When an exception is thrown while generating debug information, whatever started the process should not stop, as illustrated in https://github.com/jitsi/libjitsi/issues/318
This commit catches all unchecked exceptions that occur while generating debug information.
> 318: Problems generating debug info should not stop initialization.

- src/org/jitsi/impl/neomedia/AbstractRTPPacketPredicate.java
- src/org/jitsi/impl/neomedia/rtcp/NACKPacket.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPFBPacket.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPHeaderUtils.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPIterator.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPREMBPacket.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPReceiverFeedbackTermination.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPTCCPacket.java
- src/org/jitsi/impl/neomedia/transform/DiscardTransformEngine.java
- src/org/jitsi/util/RTCPUtils.java
- src/org/jitsi/util/RTPUtils.java
- src/org/jitsi/util/function/TimestampPacketTranslation.java
Also moves RTCPHeaderUtils to util.RTCPUtils
> Adds a looksLikeRtcp utility method

- pom.xml
- src/org/jitsi/impl/neomedia/MediaUtils.java
Make sure MediaUtils got loaded if FFmpeg class fails to load.
> Updates jitsi-lgpl-dependencies to a90c574.

- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackDesc.java
- src/org/jitsi/impl/neomedia/rtp/RTPEncodingDesc.java
- src/org/jitsi/util/TimeSeriesLogger.java
Provides https://github.com/jitsi/jitsi-videobridge/pull/668
> fix: Chrome 67 simulcast compatibility.

- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorAbsSendTime.java
I've already set the RemoteBitrateEstimatorAbsSendTime level to FINE on beta
> log: Reduce the log level of logs from RBEAST.

- src/org/jitsi/impl/neomedia/transform/TransformInputStream.java
After merging https://github.com/jitsi/libjitsi/pull/452.
> Fixes build.

- src/org/jitsi/service/neomedia/RTPExtension.java
Adds the video content type RTP header extension URN and updates the URN of the framemarkings RTP header extension.
> Adds a new RTP header extension URN and updates the URN of an existing one.

- src/org/jitsi/impl/neomedia/ProcessorUtility.java
- src/org/jitsi/impl/neomedia/device/VideoMediaDeviceSession.java
- src/org/jitsi/impl/neomedia/recording/RecorderRtpImpl.java
- src/org/jitsi/impl/neomedia/rtp/translator/RTPConnectorImpl.java
- src/org/jitsi/impl/neomedia/rtp/translator/RTPTranslatorImpl.java
- src/org/jitsi/impl/neomedia/transform/dtls/DatagramTransportImpl.java
- src/org/jitsi/impl/neomedia/transform/zrtp/ZRTPTransformEngine.java
Clearing up some threads after extensive testing with jigasi calling.
> Cleanup calls

- CONTRIBUTING.md
> Fixes wrong link.

- src/native/build.xml
> JAWT Rendering: Find shared library in Linux.

- pom.xml
- src/org/jitsi/impl/neomedia/codec/audio/opus/Opus.java
- src/org/jitsi/impl/neomedia/codec/audio/speex/Speex.java
- src/org/jitsi/impl/neomedia/codec/video/VPX.java
- src/org/jitsi/impl/neomedia/device/CoreAudioDevice.java
- src/org/jitsi/impl/neomedia/imgstreaming/ScreenCapture.java
- src/org/jitsi/impl/neomedia/jmfext/media/protocol/directshow/DSFormat.java
- src/org/jitsi/impl/neomedia/jmfext/media/protocol/directshow/DSManager.java
- src/org/jitsi/impl/neomedia/jmfext/media/protocol/video4linux2/Video4Linux2.java
- src/org/jitsi/impl/neomedia/jmfext/media/protocol/wasapi/WASAPI.java
- src/org/jitsi/impl/neomedia/jmfext/media/renderer/video/JAWTRenderer.java
- src/org/jitsi/impl/neomedia/portaudio/Pa.java
- src/org/jitsi/impl/neomedia/pulseaudio/PA.java
- src/org/jitsi/impl/neomedia/quicktime/CVImageBuffer.java
- src/org/jitsi/impl/neomedia/quicktime/CVPixelBufferAttributeKey.java
- src/org/jitsi/impl/neomedia/quicktime/NSObject.java
- src/org/jitsi/impl/neomedia/recording/WebmWriter.java
- src/org/jitsi/impl/neomedia/transform/srtp/OpenSSLWrapperLoader.java
- src/org/jitsi/sctp4j/Sctp.java
Fixes loading native dependencies in real OSGi environment.
> Updates to using latest jitsi-utils.

- .github/workflows/maven.yml
- pom.xml
- src/org/jitsi/impl/configuration/ConfigurationServiceImpl.java
- src/org/jitsi/impl/fileaccess/FailSafeTransactionImpl.java
- test/org/jitsi/impl/configuration/TestConfigurationService.java
- test/org/jitsi/impl/configuration/TestConfigurationServicePersistency.java
- test/org/jitsi/impl/fileaccess/TestFailSafeTransaction.java
- test/org/jitsi/impl/fileaccess/TestFileAccessService.java
- test/org/jitsi/util/xml/TestXMLUtils.java
While fiddling in Jitsi, I found some tests that actually belong to libjitsi but weren't migrated when libjitsi was pulled out.
> Transfer some tests from Jitsi Desktop
