- src/org/jitsi/impl/neomedia/device/PulseAudioSystem.java
This prevents any device registered as a different format from
showing up in the device list.
This can be reproduced by overriding the pulseaudio default for sample rate in /etc/pulse/daemon.conf
default-sample-format = s32le
This condition prevented one of two sound cards from appearing in the device list only for pulseaudio. PortAudio worked Ok when selecting the "default" devices and configuring pulseaudio appropriately. It was clear that the sound card was fully functional. After removing this condition, the sound card now appears (and functions) as expected in both capture and playback device lists.
Without commentary in the code, it's unclear to me as to why this condition is present at all.
> Remove condition for S16LE sample format

- src/org/jitsi/impl/neomedia/codec/video/h264/JNIDecoder.java
Created as an addon for issue #28
> Input buffer timestamp used instead of setting as unknown

- src/native/vpx/README.md
the typo is easy for people (like me) to copy and make mistakes, since there exists another target named 'libvpx'.
> correct a command in README.md

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/transform/DebugTransformEngine.java
- src/org/jitsi/service/packetlogging/PacketLoggingConfiguration.java
- src/org/jitsi/service/packetlogging/PacketLoggingService.java
I had this lying around for a while and I thought that it might be helpful for somebody else. It requires some change in the PacketLoggingServiceImplementation as well so that it actually logs ARBITRARY packets.
You can setup logging like this:
```
net.java.sip.communicator.packetlogging.PACKET_LOGGING_ENABLED=true
net.java.sip.communicator.packetlogging.PACKET_LOGGING_ARBITRARY_ENABLED=true
net.java.sip.communicator.packetlogging.PACKET_LOGGING_FILE_COUNT=1
net.java.sip.communicator.packetlogging.PACKET_LOGGING_FILE_SIZE=-1
```
You setup a named pipe like this:
```
mkfifo ~/.sip-communicator/log/jitsi0.pcap
```
You launch Wireshark like this:
```
wireshark -k -i <(cat ~/.sip-communicator/log/jitsi0.pcap)
```
> Adds a DebugTransformEngine.

- src/org/jitsi/impl/neomedia/device/MediaDeviceSession.java
Forcing channels to Format.NOT_SPECIFIED negates the check in the "if" block on line 1594. Getting the specified channels from the AudioFormat would seem to be more effective.
> Modified audio channel retrieval

- src/org/jitsi/impl/neomedia/transform/CachingTransformer.java
This pull requests makes nack cache settings configurable out of .sip-communicator.properties. Settings include: 
-Max number of packets
-Number of streams to cache
-Max milliseconds of data to
> Config cache

- src/org/jitsi/impl/neomedia/transform/RetransmissionRequester.java
retransmission was requested with a NACK. Such cases would indicate (unless the RTT
is <10ms) that the NACK was not necessary.
> Logs a message whenever a packet arrives less than 10ms after its

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
when jitsi-videobridge performs health checks. We cannot rely on it
being closed with #transformEngineChain, because the chain isn't always
initialized (when helath-checks are run on jitsi-videobridge, it creates
MediaStreams but never sets their RTPConnector, so the chain is never
created.
> Closes #cachingTransformer on MediaStreamImpl#close(), fixing a leak

- src/org/jitsi/impl/neomedia/transform/dtls/DtlsControlImpl.java
No reasons to compute a new cert with the same keypair
> Also cache certificate and fingerprint in DtlsControlImpl

- src/org/jitsi/impl/neomedia/transform/dtls/CertificateInfo.java
- src/org/jitsi/impl/neomedia/transform/dtls/DatagramTransportImpl.java
- src/org/jitsi/impl/neomedia/transform/dtls/DtlsControlImpl.java
- src/org/jitsi/impl/neomedia/transform/dtls/DtlsPacketTransformer.java
- src/org/jitsi/impl/neomedia/transform/dtls/DtlsTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/dtls/Properties.java
- src/org/jitsi/impl/neomedia/transform/dtls/TlsClientImpl.java
- src/org/jitsi/impl/neomedia/transform/dtls/TlsServerImpl.java
- src/org/jitsi/impl/neomedia/transform/zrtp/ZrtpControlImpl.java
- src/org/jitsi/service/neomedia/AbstractSrtpControl.java
- src/org/jitsi/service/neomedia/SrtpControl.java
The following modifications were applied while trying to remove a 1 second hard minimum on connectivity establishment between Videobridge and Chrome/WebRTC. Related modifications in jitsi-videobridge (i.e. which will be introduced in a branch there with the same name) (will) depend on these.
Of separate interest is commit 32c3e34 which fixes a long-standing issue of breaking DTLS flights into multiple UDP packets. The fix is desirable in the context of optimizing the connectivity establishment i.e. this PR.
> Unbreak DTLS flights

- src/org/jitsi/impl/neomedia/transform/dtls/Properties.java
21:31:50 JVB 2016-03-28 21:31:50.687 WARNING: [51] org.jitsi.videobridge.Conference.warn() Failed to close an IceUdpTransportManager of conference c8c2854fc6074e59!
21:31:50 java.lang.NullPointerException
21:31:50   at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
21:31:50   at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
21:31:50   at org.jitsi.impl.neomedia.transform.dtls.Properties.put(Properties.java:132)
21:31:50   at org.jitsi.impl.neomedia.transform.dtls.DtlsControlImpl.start(DtlsControlImpl.java:767)
21:31:50   at org.jitsi.videobridge.IceUdpTransportManager.close(IceUdpTransportManager.java:626)
21:31:50   at org.jitsi.videobridge.Conference.closeTransportManager(Conference.java:307)
21:31:50   at …
> Fixes a NullPointerException. (Reported by Damyan Minkov.)

- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcRewriter.java
- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcRewritingEngine.java
Suppose we have a frame being transmitted in 10 packets with timestamp
X. Our RTP timestamp rewriting is supposed to rewrite X -> Y. We have
observed that, under certain circumstances, our RTP timestamp rewriting
can start by rewriting X -> Y for the first few packets, and then X -> Z
for the rest of the packets. The circumstances under which this problem
manifests is when we receive an update for the remote clock -through RTCP-.
> Attempts to fix frequent short freezes.

- pom.xml
- src/org/jitsi/impl/neomedia/transform/srtp/CryptoBenchmark.java
NIOBlockCipher as been removed in PR #97
commit 18c951646db8d748f17d6aaeb7feec37439266f9
This was missed because CryptoBenchmark.java was excluded
in maven compilation, so don't exclude it
This fixes #132 (Broken Ant build)
> Remove reference to NIOBlockCipher in CryptoBenchmark

- src/org/jitsi/impl/neomedia/transform/dtls/TlsClientImpl.java
- src/org/jitsi/impl/neomedia/transform/dtls/TlsServerImpl.java
As discussed when we were implementing DTLS cert cache (#98),
we want to enforce Perfect Forward Secrecy,
so that server compromise as no effect on past conferences.
On the client side Firefox is already enforcing it since v38
https://hacks.mozilla.org/2015/02/webrtc-requires-perfect-forward-secrecy-pfs-starting-in-firefox-38/
(don't know about chrome)
Tested with Firefox 44, Firefox Nightly 47 and Chrome 49
> Enforce Perfect Forward Secrecy for DTLS

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
If the transform engine chain was never initialized, the retransmission
requester will not be closed as part of the chain. Close it
separately.
> Closes the retranmission requester.

- doc/parameters.md
Created a list of all sip-communicator.properties (or System) variables that libjitsi uses at the moment.
> Initial documentation of ConfigurationService parameters added

- src/org/jitsi/impl/neomedia/transform/dtls/DtlsControlImpl.java
- src/org/jitsi/util/ConfigUtils.java
This pull request is a replacement of https://github.com/jitsi/libjitsi/pull/67 which is now obsolete.
Here is a sample of property settings made available and being set:
org.jitsi.impl.neomedia.transform.dtls.RSA_KEY_SIZE_CERTAINTY=80
org.jitsi.impl.neomedia.transform.dtls.RSA_KEY_SIZE=2048
org.jitsi.impl.neomedia.transform.dtls.CERT_CACHE_EXPIRE_TIME=60000
<s>org.jitsi.impl.neomedia.transform.dtls.CERT_VALIDITY_TIME=43200000</s>
The jitsi-meet server administrator can set the number of key bits (...RSA_KEY_SIZE), set the certificate cache expire time (...CERT_CACHE_EXPIRE_TIME=0 for the "old" way should mean new certificate on every connection), and how long the certificate is valid for after the time of generation (...CERT_VALIDITY_TIME is above set to 12 hours). Times are in …
> Configurable DTLS certificate generation parameters.

- test/org/jitsi/sctp4j/SctpTransferTest.java
- test/org/jitsi/sctp4j/TestLink.java
Communicate that testing is happening and differentiate test outcomes.
Tried a couple of fixed seed values that would still exercise the
tests but complete in under a minute on my machine.
Test consistently passes and in a reasonable amount of time.
Formatting.
This PR is a replacement for https://github.com/jitsi/libjitsi/pull/77 (when force pushing updates to that branch, all the comments disappeared).
> Use fixed Random seed values and a latch for test consistency.

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/RawPacket.java
- src/org/jitsi/impl/neomedia/transform/RetransmissionRequesterImpl.java
- src/org/jitsi/impl/neomedia/transform/rewriting/ExtendedSequenceNumberInterval.java
- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcGroupRewriter.java
- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcRewriter.java
- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcRewritingEngine.java
- src/org/jitsi/util/RTPUtils.java
This PR contains some fixes for RTP timestamp rewriting which will help reduce the number of freezes during a simulcast enabled conference.
> Timestamp fixes.

- src/org/jitsi/impl/neomedia/codec/REDBlockIterator.java
- src/org/jitsi/impl/neomedia/recording/SynchronizerImpl.java
- src/org/jitsi/impl/neomedia/transform/AbsSendTimeEngine.java
- src/org/jitsi/impl/neomedia/transform/REDTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/rtcp/CompoundPacketEngine.java
- src/org/jitsi/sctp4j/SctpNotification.java
bytes in java are signed, and when you convert them to a
bigger type, like int, java perform what we call sign extension
and FF become FFFFFFFF before you shift (<<),
giving you unexpected result (compared to C)
Found using FindBugs
http://findbugs.sourceforge.net/bugDescriptions.html#BIT_ADD_OF_SIGNED_BYTE
http://findbugs.sourceforge.net/bugDescriptions.html#BIT_IOR_OF_SIGNED_BYTE
> Fix possible byte conversion bug

- src/org/jitsi/impl/neomedia/DominantSpeakerIdentification.java
Two different Long objects A and B can have the same value
giving true for A.equals(B) but false for A == B
Found using FindBugs
http://findbugs.sourceforge.net/bugDescriptions.html#RC_REF_COMPARISON
> Compare Long using equals and not ==

- test/org/jitsi/impl/neomedia/transform/srtp/SRTPCipherCTRTest.java
The jnopenssl JNA library is only available for Linux. So don't attempt
to run the test anywhere else.
> Ignore OpenSSL AES test when not running on Linux

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
Math.abs(Long.MIN_VALUE) == Long.MIN_VALUE which is negative
https://docs.oracle.com/javase/7/docs/api/java/lang/Math.html#abs%28long%29
Before this commit
0 <= localSourceID < Integer.MAX_VALUE
or localSourceID == (Long.MIN_VALUE % Integer.MAX_VALUE) == -2
After
0 <= localSourceID <= Integer.MAX_VALUE
This was found using FindBugs
http://findbugs.sourceforge.net/bugDescriptions.html#RV_ABSOLUTE_VALUE_OF_RANDOM_INT
> Ensure localSourceID is positive

- src/org/jitsi/impl/neomedia/MediaStreamStatsImpl.java
If RTT is really small (<1ms, like in a test setup), we might
end up with negative ntprtd value, but less than 1ms, which
we can round to 0. This is normal because timeMs is System.currentTimeMillis(),
so the (im)precision is 1ms at best.
> Rework getRoundTripDelay to reduce 'RTT computation may be wrong'

- src/org/jitsi/impl/neomedia/transform/sdes/SDesTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/srtp/AES.java
- src/org/jitsi/impl/neomedia/transform/srtp/BaseSRTPCryptoContext.java
- src/org/jitsi/impl/neomedia/transform/srtp/BlockCipherFactory.java
- src/org/jitsi/impl/neomedia/transform/srtp/SRTPCipherCTRJava.java
- src/org/jitsi/impl/neomedia/transform/srtp/SecurityProviderBlockCipherFactory.java
The introduction of the various cipher factories ignored AES192/256, which can be used by ZRTP. SDES was partially broken too, but had the option in the UI for a while.
> Restore AES192/256 SRTP functionality

- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcGroupRewriter.java
This commit attempts to fix the (now very rare) scrambling video problem
that we have been observing in our deployments. In particular, there's
no reason to enforce a threshold for the RTP timestamp uplifting. If
packets with old timestamps reach a receiver's jitter buffer they can
break the decoding process.
> Always uplifts RTP timestamps upon rewriting.

- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcGroupRewriter.java
When we rewrite the first frame, the maxTimestamp is equal to 0. If the
delta is less than 0, we erroneously rewrite the RTP timestamp of that
frame into 1.
> Fixes a bug in RTP timestamp uplifting.

- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcGroupRewriter.java
- src/org/jitsi/impl/neomedia/transform/rewriting/SsrcRewritingEngine.java
Makes sure we update the minTimestamp value when we perform RTP
timestamp uplifting. Failure in doing so may result in maxTimestamp
not being updated, breaking RTP timestamp uplifting.
> RTP timestamp uplifting fixes

- src/org/jitsi/sctp4j/Sctp.java
Attempts to fix a failure to accept() an SCTP socket in
jitsi-videobridge. We observed the following log:
No SctpSocket found for ptr: 140437445429440
> Use a ConcurrentHashMap to store sockets.

- src/org/jitsi/impl/neomedia/MediaUtils.java
- src/org/jitsi/impl/neomedia/VideoMediaStreamImpl.java
Also, starts ranges with 1 instead of 0.
Links to RFC 6236 instead of draft-ietf-mmusic-image-attributes-04.
This fixes the Jitsi bug reported here:
http://lists.jitsi.org/pipermail/users/2016-June/011253.html
> Use colons instead of dashes in a=imageattr lines.

- src/org/jitsi/impl/neomedia/transform/csrc/SsrcTransformEngine.java
It's no longer required to let some silent audio packets go through the chain because we're rewriting the sequence numbers of the audio stream.
> Drops all silent audio packets, assuming proper config.

- src/org/jitsi/impl/neomedia/recording/WebmDataSink.java
This change enables video bridge users (or other custom libjitsi projects) that solely use the stack for server side recording to enable auto keyframe control for faster seeking in recorded files and automatically correct intermittent issues. The function is controlled by a system parameter.
> Auto keyframe control for recording (fast seek)

- src/org/jitsi/impl/neomedia/recording/RecorderRtpImpl.java
This commit enables WAV recording instead of MP3 if the
org.jitsi.impl.neomedia.recording.RecorderRtpImpl.AUDIO_CODEC parameter
is set to “wav” (case insensitive)
> Add support for WAV recording with a configuration value

- src/org/jitsi/impl/neomedia/rtcp/RemoteClockEstimator.java
- src/org/jitsi/impl/neomedia/rtp/translator/OutputDataStreamImpl.java
Takes RTP timestamp wrap-around when calculating the RTP clock frequency.
> fix(rewriting): Fixes the RTP clock frequency calculation.

- src/org/jitsi/impl/neomedia/codec/video/h264/DePacketizer.java
This was left behind in our local branch related to
https://github.com/jitsi/libjitsi/pull/183
> Fix the array out of bound issue in keyframe detection

- src/org/jitsi/impl/neomedia/rtp/translator/RTCPFeedbackMessageSender.java
Makes sure that the keyframe requesters are registered with the recurring runnable executor.
> fix: keyframe requester periodic execution registration.

- src/org/jitsi/service/neomedia/MediaType.java
Jitsi currently fails to parse some INVITEs in a SIP call with valid media types. These new media types added to the enum are all listed in RFCs and we should be able to parse them without throwing an exception.
#1 introduced the MESSAGE media type and it didn't cause a break where we iterate over the enum. So this should be safe to merge as well.
> Add support for media types listed in the IANA registry

- src/org/jitsi/impl/neomedia/RawPacket.java
- src/org/jitsi/impl/neomedia/transform/csrc/CsrcTransformEngine.java
This property is useful when a SIP Provider does not support the list of contributing sources in its SIP infrastructure. If one is having annoying noise issues, this property may solve it when it is set to true.
> Add org.jitsi.impl.neomedia.RawPacket.DISCARD_CONTRIBUTING_SOURCES config property

- src/org/jitsi/impl/neomedia/rtp/FrameDesc.java
- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackDesc.java
- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackReceiver.java
- src/org/jitsi/impl/neomedia/rtp/RTPEncodingDesc.java
- src/org/jitsi/impl/neomedia/rtp/translator/SimulcastController.java
This removes the key frame packet piggybacking from the ingress and also reworks the stream drop detection, and also ignores late re-ordered/late key frames.
> fix: Removes key frame packet piggybacking.

- src/org/jitsi/impl/neomedia/transform/RtxTransformer.java
I see a "failed to retransmit"  message being logged, and while I don't know what the reason is, it seems to make sense to not count them towards the retransmitted bytes.
> fix: Don't count packets which failed to retransmit.

- src/org/jitsi/impl/neomedia/rtp/FrameDesc.java
- src/org/jitsi/impl/neomedia/rtp/RTPEncodingDesc.java
- src/org/jitsi/impl/neomedia/rtp/translator/BitstreamController.java
- src/org/jitsi/impl/neomedia/rtp/translator/SimulcastController.java
The two major changes are  1st the fact that we now use a separate `BitstreamController` when a stream is suspended (when a receiver doesn't have enough bandwidth). This allows us to treat suspension/resumption the same way as a simulcast layer switch, removing unnecessary complexity from the BitstreamController that shapes an RTP stream and 2nd how we update the target quality index.
> Fixes around adaptivity RTP stream shaping

- src/org/jitsi/impl/neomedia/rtcp/RTCPReceiverFeedbackTermination.java
- src/org/jitsi/impl/neomedia/transform/RtxTransformer.java
- src/org/jitsi/impl/neomedia/transform/rtcp/StatisticsEngine.java
NACKs should be consumed by the re-transmission logic and not forwarded to senders
> Do not forward nack

- src/org/jitsi/util/RTPUtils.java
The comparison using the '==' operator /only/ checks for reference equality of the Integers, which is very likely not what was intended here. This PR adds a check for value equality by unboxing.
More alerts here: https://lgtm.com/projects/g/jitsi/libjitsi/
Link to this specific alert: https://lgtm.com/projects/g/jitsi/libjitsi/snapshot/3d13c1d8472e4f03be224dc3343ee25d817a26fd/files/src/org/jitsi/util/RTPUtils.java#L199
Tip: enable PR integration on lgtm.com for automatic code reviews. They'll catch this sort of problem before it gets merged.
> Fix lgtm.com alert: unintentional comparison using '==' operator only tests for reference equality

- src/org/jitsi/impl/neomedia/transform/RtxTransformer.java
Currently the FF webrtc engine ignores our bandwidth probing (https://bugzilla.mozilla.org/show_bug.cgi?id=1362450), so we want to disable bandwidth probing for FF. FF also does not support RTX. This method will be used by the bridge to determine whether the destination endpoint has RTX or not. If not, then that would indicate a FF destination endpoint and it will disable adaptivity for that endpoint.
> feat: Adds the RtxTransformer.destinationSupportsRtx() method.

- src/org/jitsi/impl/neomedia/MediaStreamStatsImpl.java
- src/org/jitsi/impl/neomedia/stats/AbstractTrackStats.java
- src/org/jitsi/impl/neomedia/stats/MediaStreamStats2Impl.java
- src/org/jitsi/service/neomedia/RawPacket.java
Empty Receiver Reports used to be incorrectly detected
as invalid packets, resulting in getRTCPSSRC() returning -1 (and
possibly other bugs).
> Fixes the isInvalid check for RTCP

- src/org/jitsi/service/neomedia/RawPacket.java
Fixes a bug in which RawPacket#buffer changes, but
the packet's HeaderExtensions still use the old instance.
> fix: Fixes a failure to set abs-send-time correctly.

- src/org/jitsi/impl/neomedia/rtcp/RTCPReceiverFeedbackTermination.java
- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackDesc.java
Zero length packets can make our SRTP stack to crash, so instead of
letting them through, return null.
> Zero length rtcp fix

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/rtp/FrameMarkingHeaderExtension.java
The patch was going to be more ambitious as IMHO the RawPacket should be passed from the top layers instead of buff,off,len ... but it was not working so I decided to go KISS first
In order to have simulcast enabled with media encryption it is required to disable the vp8 extended pic id on videobridge:
```
org.jitsi.videobridge.ENABLE_VP8_PICID_REWRITING=false
```
cc/ @bgrozev
> Retrieve Spatial and Temporal layer ids from frame marking header extension

- src/org/jitsi/impl/neomedia/codec/FMJPlugInConfiguration.java
Arrays.asList creates a List<> that is backed by the original array. It doesn't accept adding elements, thus adding the FFMpeg codecs would later fail. Fix this by using a regular list.
> Fix FMJ codec registration when FFMpeg is enabled

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/MediaStreamStatsImpl.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPFBPacket.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPReceiverFeedbackTermination.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPTCCPacket.java
- src/org/jitsi/impl/neomedia/rtp/TransportCCEngine.java
- src/org/jitsi/impl/neomedia/transform/rtcp/StatisticsEngine.java
- test/org/jitsi/impl/neomedia/rtcp/RTCPTCCPacketTest.java
- Propagates RTT to the send-side delay-based controller.
- Partially reverts most of the RTCP TCC parsing changes that were
introduced in e019b4217daa3967efa457c299f76c1f92e012f3.
- Uses correct SSRCs in the outgoing RTCP TCC packets.
- Fixes a synchronization which could lead to undefined behavior of the
Java Map.
> WIP: Implements send-side bandwidth estimations.

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/VideoMediaStreamImpl.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPReceiverFeedbackTermination.java
- src/org/jitsi/impl/neomedia/rtcp/RTCPTCCPacket.java
- src/org/jitsi/impl/neomedia/rtp/TransportCCEngine.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/AimdRateControl.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/InterArrival.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/OveruseDetector.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/OveruseEstimator.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorAbsSendTime.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorSingleStream.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorWrapper.java
- src/org/jitsi/impl/neomedia/rtp/sendsidebandwidthestimation/BandwidthEstimatorImpl.java
- src/org/jitsi/impl/neomedia/rtp/sendsidebandwidthestimation/SendSideBandwidthEstimation.java
- src/org/jitsi/service/neomedia/RawPacket.java
- src/org/jitsi/util/DiagnosticContext.java
- test/org/jitsi/impl/neomedia/rtcp/RTCPTCCPacketTest.java
- The first idea is to be able to mine our infra logs for valuable information and be able to correlate different logs together at the conference level or at the user level. We already to that in the JVB code and this PR enables the same logic in LJ.
- Additionally this PR also includes fixes for the send-side bandwidth estimations.
> Fixes send-side bandwidth estimations and enables log mining.

- src/org/jitsi/impl/neomedia/transform/rtcp/StatisticsEngine.java
We observed an instance in which one browser connected to jitsi-videobridge was continually sending invalid RTCP SR packets (with either 'rc' or 'length' being incorrect). The bridge would forward them (and it shouldn't forward SRs at all). This makes it drop RTCP packets when parsing fails instead.
> fix: Drops RTCP packets which failed to be parsed.

- src/org/jitsi/impl/neomedia/rtp/TransportCCEngine.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/AimdRateControl.java
- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorAbsSendTime.java
- src/org/jitsi/impl/neomedia/rtp/sendsidebandwidthestimation/SendSideBandwidthEstimation.java
- src/org/jitsi/util/DiagnosticContext.java
- src/org/jitsi/util/Logger.java
- src/org/jitsi/util/TimeSeriesLogger.java
- src/org/jitsi/util/TimeSeriesPoint.java
With this PR all time series can be handled separately from the general purpose logging logic:
timeseries.level = ALL
timeseries.org.jitsi.impl.neomedia.rtp.remotebitrateestimator.RemoteBitrateEstimatorAbsSendTime.level = OFF
timeseries.useParentHandlers = false
timeseries.handlers = java.util.logging.FileHandler
> logs: Use a separate logger for logging time series.

- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackReceiver.java
when a MediaStreamTrackReceiver has no tracks.
> fix: Uses an emprty array instead of null

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
This PR solves the following problem:
If RED was enabled our clients could not receive video (jitsi-videobridge dropped the packets because it could not identify correctly if there were keyframes).
REDBlockIterator.getPrimaryBlock(...) requires the offset and length of the RTP payload but the whole packet's parameters were passed.
> Fix getting primary block of RED packets

- pom.xml
- src/org/jitsi/impl/neomedia/transform/csrc/CsrcAudioLevelDispatcher.java
- src/org/jitsi/impl/neomedia/transform/csrc/CsrcTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/csrc/SsrcTransformEngine.java
Currently there are `N` threads created by `CsrcAudioLevelDispatcher`, `1` per each incoming audio stream, for `20` conferences with `3` peers each there are `60` threads created, even so cached thread pool used. Most of the time these threads are blocked in waiting state.
This pull request rework `CsrcAudioLevelDispatcher` to use common `ForkJoinPool` to asynchronously dispatch audio level updates to media stream.
> Eliminate too many CsrcAudioLevelDispatcher threads.

- pom.xml
- src/org/jitsi/impl/neomedia/MediaUtils.java
Make sure MediaUtils got loaded if FFmpeg class fails to load.  fix searching for h264 codec.
> Updates jitsi-lgpl-dependencies to a90c574. (#420)

- src/org/jitsi/impl/neomedia/device/CoreAudioDevice.java
- src/org/jitsi/impl/neomedia/device/DeviceConfiguration.java
- src/org/jitsi/util/OSUtils.java
- Vista is out of support since April 2017
- XP was the last OS without WASAPI support, so remove checks that
did stuff only on 'new' Windows versions
Closes #304
> Add Windows 10 to OS Utils, remove Windows Vista

- src/org/jitsi/impl/neomedia/AbstractRTPPacketPredicate.java
- src/org/jitsi/impl/neomedia/transform/DiscardTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/REDTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/csrc/CsrcTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/csrc/SsrcTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/dtmf/DtmfTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/fec/FECSender.java
- src/org/jitsi/impl/neomedia/transform/pt/PayloadTypeTransformEngine.java
- src/org/jitsi/service/neomedia/RawPacket.java
- src/org/jitsi/util/RTCPUtils.java
as it was returning false for RTP packets with sequence number 0. It also removes some unused code.
> Fixes AbstractRTPPacketPredicate.test()

- src/org/jitsi/impl/neomedia/AbstractRTPPacketPredicate.java
- src/org/jitsi/impl/neomedia/transform/DiscardTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/REDTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/csrc/CsrcTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/csrc/SsrcTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/dtmf/DtmfTransformEngine.java
- src/org/jitsi/impl/neomedia/transform/fec/FECSender.java
- src/org/jitsi/impl/neomedia/transform/pt/PayloadTypeTransformEngine.java
- src/org/jitsi/service/neomedia/RawPacket.java
- src/org/jitsi/util/RTCPUtils.java
https://github.com/jitsi/libjitsi/commit/505f2d5b646efb2acd18bb83038d095a088a5a71 broke jigasi DTLS connection establishment. This commit, instead of changing how RawPacket.isInvalid() works, it introduces a RawPacket.isRtpRtcp() method -moved from RTCPUtils and patched so as to properly validate RTP packets with sequence number 0-.
It looks like RawPacket.isInvalid() is used to validate other types of packets, notably DTLS packets, even tho it misleadingly bases its checks on minimum lengths of RTP/RTCP packets.
> Fix Jigasi DTLS connection establishment.

- src/org/jitsi/impl/neomedia/transform/dtls/DtlsPacketTransformer.java
BouncyCastle introduced behavior between its 1.54 release (currently used in libjitsi) and 1.59. It now clears the master secret from its session parameters immediately after establishing a connection, making them unavailable for exporting keying material. The value can still be present in the session parameters that can be retrieved from the resumable session exposed by the TLS context.
This commit attempts to retrieve the master secret from a resumable session, if that value is not available from the session parameters on the context. This commit should not introduce functional changes when used with BouncyCaste 1.54, but does allow the code to be executed in an environment that has a later version of BouncyCastle.
This change stems from discussions …
> Export master secret from resumable session, when not available on context

- src/org/jitsi/impl/neomedia/AudioMediaStreamImpl.java
- src/org/jitsi/impl/neomedia/device/AudioMediaDeviceImpl.java
In case of jigasi in translator mode we want to receive those levels and
we need to signal that we support it on offer/answer.
> Lets device advertise/support ssrc audio levels extension (rfc6464).

- src/org/jitsi/impl/neomedia/recording/RecorderRtpImpl.java
RTPConnectorImpl, which when constructed creates a new
FECTransformEngine instance, passing in the current value of
mediaStream, which is null and initialized afterwards.
This is probably what is causing the issue in this following forum post
regarding jigasi:
https://community.jitsi.org/t/problems-implementing-rtptanslation-in-jigasi-for-transcriptiongateway/15744
And I am wanting to internally use the old Colibri recording method,
which I realize is no longer supported, but I think this is just plainly
broken, and maybe has other implications.
> RecorderRtpImpl.java is constructing an instance of the inner class

- src/org/jitsi/impl/neomedia/RTPConnectorInputStream.java
- src/org/jitsi/impl/neomedia/transform/SinglePacketTransformer.java
**TL; DR**:
Micro-optimization applied on hotpath's found by profiling.
**Problem**:
1. According to Oracle Visual VM there is small but noticeable overhead introduced by method references used in [`reverseTransform`](https://github.com/jitsi/libjitsi/blob/cc9b594edc504c08f79f6d5a767f255671f03693/src/org/jitsi/impl/neomedia/transform/SinglePacketTransformer.java#L128) and [`transform`](https://github.com/jitsi/libjitsi/blob/cc9b594edc504c08f79f6d5a767f255671f03693/src/org/jitsi/impl/neomedia/transform/SinglePacketTransformer.java#L151);
1. A memory traffic caused by allocating new nodes by `LinkedBlockingQueue` in the [`RTPConnectorInputStream`](https://github.com/jitsi/libjitsi/blob/cc9b594edc504c08f79f6d5a767f255671f03693/src/org/jitsi/impl/neomedia/RTPConnectorInputStream.java#L170) …
> Micro optimizations on hotpaths

- src/org/jitsi/impl/neomedia/codec/video/vp8/DePacketizer.java
- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackDesc.java
- src/org/jitsi/impl/neomedia/rtp/MediaStreamTrackReceiver.java
- src/org/jitsi/util/RTPUtils.java
partially reverts 96ffe607. 96ffe607 adds some logging around rtp encodings matching that has some negative side effects. The logging logic is best suited for the caller so it has been/will be moved there.
> Debug logging of packet mishandling round 2

- src/org/jitsi/impl/neomedia/rtp/remotebitrateestimator/RemoteBitrateEstimatorWrapper.java
This has been turned on in the bridge for a long time, and I'd like to remove the code which enables it: https://github.com/jitsi/jitsi-videobridge/blob/master/src/main/java/org/jitsi/videobridge/osgi/JvbBundleConfig.java#L151
> Switch AST to default to true.

- src/org/jitsi/impl/neomedia/codec/audio/amrwb/JNIEncoder.java
AudioFormat.computeDuration(.) of the Java Media Framework (JMF) returns -1 on default. Therefore, the timestamp in RTP started with 0xffff and decreased by one with each packet. Now, the timestamp increases 320 with every packet (because just a single AMR-WB frame is included in each packet).
fixes jitsi/jitsi#613
> AMR: Send correct timestamp in RTP packets.

- src/org/jitsi/impl/neomedia/codec/video/h263p/JNIEncoder.java
The source code contains a line of code which is about the rate-control equation (rc_eq). The given one does not work with the default H.263+ encoder in Debian/Ubuntu and gives the error messages `Unknown function` and `Error parsing`. Because that line of code is commented/disabled anyway, it is simply removed.
> H.263+: Remove non-working commented setting.

- src/org/jitsi/impl/neomedia/codec/video/h264/JNIEncoder.java
The rate-control equation (rc_eq) cannot be set for this encoder, at least not in the default encoder for Debian/Ubuntu. Furthermore, I am not aware of any H.264 encoder which allows this. FFmpeg ignores unknown options silently. Because FFmpeg 4 moved that option to the private options and removed that public symbol completely, and because that option does not do anything in H.264, it is simply removed.
> H.264: Remove non-working setting rate-control equation.

- src/org/jitsi/impl/neomedia/codec/video/h263p/JNIEncoder.java
The motion-estimation method (me_method) cannot be set for this encoder, at least not in the default encoder for Debian/Ubuntu. Furthermore, I am not aware of any H.263+ encoder which allows this. FFmpeg ignores unknown options silently. Because FFmpeg 4 moved that option to the private options and removed that public symbol completely, and because that option does not do anything in H.263+, it is simply removed.
> H.263+: Remove non-working setting me_method.

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
The initial change was made in 912998b9, but was not taking in
consideration that all jitsi desktop video calls have a rtpTranslator,
and that change broke incoming video.
As this change is needed for jigasi, jigasi always sets useTranslator
for the audio and that setting is only used in that case.
fixes jitsi/jitsi#627
closes https://github.com/jitsi/libjitsi/pull/505
Thanks @traud for finding it.
> Fixes receiving remove videos.

- pom.xml
Otherwise, sometimes (not reproducible), JAWT Rendering is not able to load the class sun.awt.x11.XErrorHandlerUtil.
> Apache Felix (OSGi): Allow X11 to the Java Classloader.

- src/org/jitsi/impl/neomedia/codec/video/h264/JNIEncoder.java
With FFmpeg 2.7, the motion-estimation method (me_method) was moved from a public symbol to the private options of the underlying encoder interface for libx264. Since FFmpeg 4.0, the public symbol me_method does not exist anymore. Because the latest supported is FFmpeg is 2.8, simply use the private-option interface instead.
> H.264: Set the motion-estimation method via private options.

- src/org/jitsi/impl/neomedia/codec/video/HFlip.java
This avoids the FFmpeg internal error message: The filters 'Parsed_buffer_0' and 'Parsed_hflip_1' do not have a common format and automatic conversion is disabled.
This happens, because the source (buffer) might use a pixel format which the filter (horizontal flip; hflip) is not able to use directly. Therefore, a conversion might be need which is enabled with the keyword scale. Because the sink (buffersink) shall have the same pixel format as the source, the same is required after the filter hflip.
closes jitsi/libjitsi#431
fixes jitsi/jitsi#540
> FFmpeg: AVFilter: HFlip: Allow conversion between pixel formats.

- src/org/jitsi/impl/neomedia/codec/audio/amrwb/JNIEncoder.java
AMR-WB is the bandwidth-efficient sibling of the HD audio codec G.722. Therefore, really leverage it features and enable voice-activation detection (VAD) so the RTP packets are transmitted discontinuously (DTX). Although this works with all versions of the encoder, at least version 0.1.5 of the OpenCORE-AMR decoder is recommended (comes in Debian 11 and Ubuntu 20.04 LTS), because previous versions had a bug in the Silence Descriptor (SID) decoding which resulted in white noise. Furthermore, to reduce the bandwidth even more, do not use the highest (AMR-WB Mode 8) but the GSM compatible bitrate as default (AMR-WB Mode 2). That still gives HD audio but works not only on UMTS (3G) but even on GSM links (2G).
> AMR-WB: Enable VAD/DTX and use GSM compatible bitrate as default.

- src/native/build.xml
Otherwise, the resulting shared library may end-up without a link to libcrypto.so.
> build: Make sure OpenSSL is linked in Shared Library.

- src/org/jitsi/impl/neomedia/MediaUtils.java
- src/org/jitsi/impl/neomedia/codec/FMJPlugInConfiguration.java
OpenH264 is an extension to FFmpeg. The bundled FFmpeg for Microsoft Windows includes support for the video codec H.264. However, that bundled FFmpeg does not come with the audio codec AMR(-WB). The change for OpenH264 simply disabled AMR-WB in general, at compile time (see #403 Review 97453424). Beside losing AMR-WB, that change was incomplete because AMR-WB is still added as a media format. For example, in Jitsi Desktop, AMR-WB is still selectable but non-functional.
This change here re-enables AMR-WB but detects whether the used FFmpeg supports AMR-WB, at runtime. Consequently, when FFmpeg is missing or when the used FFmpeg does not support AMR-WB, it does not show up in Jitsi Desktop anymore. When FFmpeg is present and when AMR-WB is supported, AMR-WB is listed and functional. On …
> AMR: Detect it within FFmpeg at Runtime.

- src/org/jitsi/service/neomedia/RawPacket.java
This was used only in jigasi and is wrong. Move it to the source.
> fix: Remove unused method.

- src/org/jitsi/impl/neomedia/AudioMediaStreamImpl.java
- src/org/jitsi/impl/neomedia/rtp/translator/RTPTranslatorImpl.java
In case of jigasi we are announcing the ssrc that will be sent early in the jingle and we want to return the ssrc from the translator/rtpManager and that to be the only value (not the random from the AudioMediaStreamImpl or -1 from RTPManagerImpl member localSSRC).
> fix: Uses ssrc from the RTPManager when translator is used.

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
In case when we autocreate OutputDataStreams we can leak threads after the mediaStream is closed and we create new OutputDataStream.
> fix: Skips injecting data in not started streams.

- src/org/jitsi/impl/neomedia/MediaServiceImpl.java
- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/transform/zrtp/ZRTPTransformEngine.java
In jigasi we saw some TimeoutProvider threads leaking ... where zrtp is not used. Seems there is a scenario in which the ZRTPTransformEngine is initialized but never stopped/cleaned. And zrtp is not used there.
Rarely happening, but still happening 20 times out of 2k.
> fix: Initialize the zrtp timeout thred only when needed.

- src/org/jitsi/impl/neomedia/MediaStreamImpl.java
- src/org/jitsi/impl/neomedia/stats/MediaStreamStats2Impl.java
> fix: Clears MediaStream stats when a receive stream is removed (by ssrc).

- src/main/java/org/jitsi/impl/neomedia/transform/dtmf/DtmfTransformEngine.java
This change is created to fix incorrect interpretations of DTMF tones.
When I send a single digit DTMF tone with a duration, for example, 1000 [sendTones](https://github.com/jitsi/lib-jitsi-meet/blob/master/JitsiConference.js#L2528)
sendTones(1, 1000)
this tone is caught by **[DtmfTransformEngine](https://github.com/jitsi/libjitsi/blob/master/src/main/java/org/jitsi/impl/neomedia/transform/dtmf/DtmfTransformEngine.java#L252)** as multiple **RawPacket**s
Every RawPacket is converted to DtmfRawPacket with isEnd boolean flag inside.
The amount of DtmfRawPackets depends on DTMF tone duration, for example
amount of 1000 - 5 packets with toEnd == false, and 3 packets with toEnd == true
amount of 2000 - 10 packets with toEnd == false, and 3 packets with toEnd == true
Then DtmfRawPackets go to …
> Incorrect interpretations of DTMF tones

- .github/workflows/maven-and-native.yml
- resources/ubuntu-build-image/Dockerfile
- resources/ubuntu-build-image/packages.sh
- resources/ubuntu-build-image/ports-sources.list
- resources/ubuntu-build-image/ppa-purge.sh
ubuntu-18.04 was deprecated and is no longer available.
ubuntu-20.04 includes various PHP versions from ppa:ondrej/php (see https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/php.sh). That ppa also includes custom packaged version of libpcre*, which break standard Ubuntu packages, namely openjdk-11-jdk. Get rid of them via ppa-purge.
The runner images for ubuntu-22.04 fortunately no longer has that stuff, see actions/runner-images#6331.
> fix: Fix github workflows.
